# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdendpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.IntegerField(choices=[(1, b'physical sample not received'), (2, b'started'), (3, b'completed')], default=2),
        ),
    ]
